# -*- coding: utf-8 -*-
"""EMS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VOyk2iT6p9vslSGU_Dl6Ypr5XAH83ehB
"""

#data
employees = {
    101: {"name": "Satya", "age": 27, "department": "HR", "salary": 50000},
    102: {"name": "Amit", "age": 30, "department": "IT", "salary": 60000},
    103: {"name": "Priya", "age": 25, "department": "Finance", "salary": 55000}
}

#add employee
def add_employee():
    try:
        emp_id = int(input("Enter Employee ID: "))
        if emp_id in employees:
            print("Employee ID already exists. Please try again.")
            return

        name = input("Enter Employee Name: ")
        age = int(input("Enter Employee Age: "))
        department = input("Enter Employee Department: ")
        salary = float(input("Enter Employee Salary: "))

        employees[emp_id] = {
            "name": name,
            "age": age,
            "department": department,
            "salary": salary
        }
        print(f"Employee {name} added successfully!\n")
    except ValueError:
        print("Invalid input. Please enter numeric values for ID, Age, and Salary.\n")

#view employees
def view_employees():
    if not employees:
        print("⚠️ No employees available.\n")
        return

    print("\n===== Employee List =====")
    print("{:<10} {:<15} {:<5} {:<15} {:<10}".format("Emp ID", "Name", "Age", "Department", "Salary"))
    print("-" * 60)

    for emp_id, details in employees.items():
        print("{:<10} {:<15} {:<5} {:<15} {:<10}".format(
            emp_id, details["name"], details["age"], details["department"], details["salary"]
        ))
    print()

#search
def search_employee():
    try:
        emp_id = int(input("Enter Employee ID to search: "))
        if emp_id in employees:
            details = employees[emp_id]
            print("\n===== Employee Details =====")
            print(f"Name       : {details['name']}")
            print(f"Age        : {details['age']}")
            print(f"Department : {details['department']}")
            print(f"Salary     : {details['salary']}\n")
        else:
            print(" Employee not found.\n")
    except ValueError:
        print(" Invalid input. Please enter a numeric Employee ID.\n")

#menu
def main_menu():
    while True:
        print("===== Employee Management System =====")
        print("1. Add Employee")
        print("2. View All Employees")
        print("3. Search for Employee")
        print("4. Exit")

        choice = input("Enter your choice (1-4): ")

        if choice == "1":
            add_employee()
        elif choice == "2":
            view_employees()
        elif choice == "3":
            search_employee()
        elif choice == "4":
            print("Thank you for using the Employee Management System. Goodbye!")
            break
        else:
            print("Invalid choice. Please select a valid option.\n")

if __name__ == "__main__":
    main_menu()